### 3주차 1일 벡터, 스칼라, 행렬, 텐서

In [2]:
from sklearn.datasets import load_iris  # 사이킷런 패키지 임포트

iris = load_iris()  # 데이터 로드
iris.data[0, :]  # 첫 번째 꽃의 데이터

array([5.1, 3.5, 1.4, 0.2])

In [1]:
x1 = np.array([[5.1], [3.5], [1.4], [0.2]])
x2 = np.array([[4.9], [3.0], [1.4], [0.2]])

In [4]:
X = np.array([[5.1, 3.5, 1.4, 0.2], [4.9, 3.0, 1.4, 0.2]])
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [5]:
x1.T # 이 때 x1이 1차원 ndarray면 전치 연산이 되지 않는다.

array([[5.1, 3.5, 1.4, 0.2]])

In [6]:
X.T

array([[5.1, 4.9],
       [3.5, 3. ],
       [1.4, 1.4],
       [0.2, 0.2]])

In [7]:
X.T.T

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

#### 연습 문제 2.1.4
- 영벡터, 일벡터, 정방행렬, 대각행렬, 항등행렬, 대칭행렬의 예를 하나씩 만들어본다.

In [14]:
A = np.zeros((5, 1))
B = np.ones((3, 1))
C = np.diag([1, 3, 5])
D = np.eye(3)
E = np.ones((3, 3))
E.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 벡터와 벡터의 곱셈 - 내적

In [15]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])

In [16]:
np.dot(x.T, y)

array([[32]])

#### 연습 문제 2.2.1
- A, B, C 세 회사의 주식은 각각 100만원, 80만원, 50만원이다. 이 주식을 각각 3주, 4주, 5주를 매수할 때 필요한 금액을 구하고자 한다.

- (1) 주식의 가격과 수량을 각각 p 벡터, n 벡터로 표시하고 넘파이로 코딩한다.

- (2) 주식을 매수할 때 필요한 금액을 곱셈으로 표시하고 넘파이 연산으로 그 값을 계산한다.


In [17]:
p = np.array([[100], [80], [50]])
n = np.array([[3], [4], [5]])

In [18]:
np.dot(p.T,n)

array([[870]])

### 3주차 2일 선형 회귀모형, 행렬 연산

#### 연습 문제 2.2.3
- 다음 코드를 실행하면 MNIST 숫자 이미지 전체 데이터를 모두 벡터로 변환하여 하나의 넘파이 행렬 X를 만든다. 이 행렬을 이용하여 다음 문제를 풀어라.
- (1) 내적을 이용하여 첫 번째 이미지와 10번째 이미지의 유사도를 구하라.
- (2) 내적을 이용하여 모든 이미지의 조합에 대해 유사도를 구하라. 어떻게 구현하는 것이 효율적일까? (힌트 : 이 문제는 뒤에서 배울 행렬과 행렬의 곱셈을 이용한다.)



In [19]:
from sklearn.datasets import load_digits
X = load_digits().data

In [25]:
d1 = X[0]
d2 = X[9]
np.dot(d1.T, d2)

2807.0

In [33]:
SIM = np.dot(X, X.T)
SIM
        

array([[3070., 1866., 2264., ..., 2812., 3006., 2898.],
       [1866., 4209., 3432., ..., 3906., 3083., 3307.],
       [2264., 3432., 4388., ..., 4005., 3063., 3697.],
       ...,
       [2812., 3906., 4005., ..., 5092., 3729., 4598.],
       [3006., 3083., 3063., ..., 3729., 4316., 3850.],
       [2898., 3307., 3697., ..., 4598., 3850., 4938.]])

#### 연습문제 2.2.4

In [34]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [35]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [36]:
A = np.array([[1], [2], [3]])
B = np.array([[4, 7], [5, 8], [6, 9]])

In [38]:
np.dot(A.T, B)

array([[32, 50]])

#### 행렬의 교환법칙과 분배법칙

In [40]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 8], [7, 6]])


In [41]:
# 교환법칙 : AB = BA (성립하지 않음)
A @ B

array([[19, 22],
       [43, 50]])

In [42]:
B @ A

array([[23, 34],
       [31, 46]])

In [43]:
# 분배법칙 : A(B + C) = AB + AC (성립함)
A @ (B + C)

array([[42, 42],
       [98, 98]])

In [44]:
A @ B + A @ C

array([[42, 42],
       [98, 98]])

#### 부분행렬

In [45]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
# (1) 


### 3주차 3일 행렬의 성질, 선형 연립방정식과 역행렬

In [1]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]  # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]

In [2]:
# W 를 구하라


array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [3]:
b

array([24. , 21.6, 34.7, 33.4])

In [8]:
Ainv = np.linalg.inv(A)
w = np.dot(Ainv, b)

In [9]:
w
# 집값은 범죄율에 반비례한다
# 공기오염도에 반비례한다.
# 방의 개수에 비례한다
# 오래된 정도에 반비례한다.

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [13]:
C = X[:, [0, 4, 5, 6]]
w, resid, rank, s = np.linalg.lstsq(C, y)
w

<ipython-input-13-5562df9a3ce7>:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  w, resid, rank, s = np.linalg.lstsq(C, y)


array([ -0.18398361, -19.39623075,   5.67359315,  -0.0227888 ])

In [11]:
w, resid, rank, s = np.linalg.lstsq(A, b)
w

<ipython-input-11-2b476ba5c8cf>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  w, resid, rank, s = np.linalg.lstsq(A, b)


array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

#### 연습문제 2.4.6

In [ ]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

In [15]:
Xpinv = np.linalg.inv(X.T @ X) @ X.T

In [16]:
w = Xpinv @ y
w

array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])

In [17]:
w, resid, rank, s = np.linalg.lstsq(X, y)
w

<ipython-input-17-82082ef33849>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  w, resid, rank, s = np.linalg.lstsq(X, y)


array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])

### 3주차 5일 선형독립과 종속, 랭크

In [1]:
# 연습문제 3.2.5
X = np.array([[1, 1], [1, 1]])
X

array([[1, 1],
       [1, 1]])

In [2]:
np.linalg.matrix_rank(X)

1

In [3]:
A = np.array([[2, 0], [0, 2]])
np.linalg.matrix_rank(A)

2